### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spotandjake** [nazmul-nhb/tinyquery#1]
Hi I wanted to embed this project into something I am working on currently and am wondering what license this code is under, as I could not find one in the repo?

**Comment by nazmul-nhb** [comment]
sorry that I couldn't reply earlier. the project is still under development. it's under MIT License. you can use it anywhere.

I only worked few hours on this project. even the readme file is incomplete, the package name shown in the readme file's import statement is wrong because it was the initial name I thought but there was already a project with similar name with a hyphen which I didn't notice first.

there might be few other issues (i'm not entirely sure). I was writing test codes but then I had some other personal works to do. so could not write all the test cases.


feel free to contribute or modify the source as your own version, I won't mind at all.
